mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import RedirectView
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from projects import views
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
urlpatterns = [
    path('admin/', admin.site.urls),
    # url('ckeditor/', include('ckeditor_uploader.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', views.home, name="index"),
    path('mainpage/', views.mainpage, name="mainpage"),
]
urlpatterns += i18n_patterns(
    path('bio/', views.bio, name="bio"),
    path('jobs/', views.jobs, name="jobs"),
    path('en/jobs/', views.jobs, name="en_jobs"),
    path('contact/', views.contact, name="contact"),
    path('job/<int:index>/', views.category, name="category"),
    path('job/all/', views.all_projects, name="all_projects"),
    path('project/<int:pk>/', views.project, name="project"),
    prefix_default_language=False,

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
from django.db import models
from django.conf import settings

from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=20, unique=5)
    # project = models.OneToOneField('Project', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

# Create your models here.


class Project(models.Model):
    LANGUAGES = (
        ('en', 'English'),
        ('es', 'Español'),
    )

    language = models.CharField(
        max_length=2,
        choices=LANGUAGES,
        default='es',
        help_text='Select language',
    )
    title = models.CharField(max_length=50, unique=True)
    image = models.ImageField()
    video = models.URLField(null=True, blank=True)
    description = RichTextField()

    CATEGORIES = (
        ('ins', 'INSTITUCIONAL'),
        ('fic', 'FICCIÓN / NO FICCIÓN'),
        ('mus', 'MÚSICA'),
        ('pol', 'POLÍTICA'),
        ('pub', 'PUBLICIDAD'),
    )
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    is_principal = models.BooleanField(default=False)
    is_shown = models.BooleanField(default=True)
    order = models.IntegerField(default=1)

    def __str__(self):
        return self.title


class Bio(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField()
    english_bio = RichTextField()
    spanish_bio = RichTextField()

    def __str__(self):
        return self.name

projects/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(required=True)
    from_email = forms.EmailField(required=True)
    affair = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}), required=True)


class ProjectsInlineForm(forms.ModelForm):
    '''ElectroporationConditionsForm.  Used to size the text input boxes'''
    class Meta:
        widgets = {'language': forms.Select(), 'title': forms.TextInput(attrs={'class': 'input_sm'}), 'image': forms.ClearableFileInput(), 'video': forms.TextInput(attrs={'class': 'input_sm'}), 'description': forms.Textarea(attrs={'class': 'text_sm'}), 'is_principal': forms.CheckboxInput(), 'is_shown': forms.CheckboxInput(), 'order': forms.NumberInput(attrs={'class': 'input_number'})
                   }

projects/views.py
from django.shortcuts import render
from django.utils import translation
from projects.models import Category, Project, Bio
from projects.forms import ContactForm
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings


# Create your views here.
def home(request):

    return render(request, 'index.html')


def mainpage(request):
    return render(request, 'mainpage.html')


def bio(request):
    obj = Bio.objects.first()
    image_url = None
    bio_description = ""
    if(obj is not None):
        image_url = obj.image.url
        if(request.LANGUAGE_CODE == 'en'):
            bio_description = obj.english_bio
        else:
            bio_description = obj.spanish_bio
    return render(request, 'bio.html', {'menu': 0, 'image': image_url, 'description': bio_description})


def jobs(request):
    categories = Project.objects.filter(is_principal=True).filter(language=request.LANGUAGE_CODE).order_by('category').order_by('order')
    return render(request, 'jobs.html', {'menu': 1, 'categories': categories})


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        name = request.POST['name']
        email = request.POST['from_email']
        affair = request.POST['affair']
        msg = request.POST['message']
        email_from = settings.EMAIL_HOST_USER
        message = "name: %s\nemail: %s\nmessage:\n%s" % (name, email, msg)
        try:
            send_mail(affair, message, email_from, ['lalo311@gmail.com'])
        except BadHeaderError:
            return HttpResponse('Failed')
        return HttpResponse('Success')
    return render(request, 'contact.html', {'menu': 2, 'form': form})


def category(request, index):
    categories = Category.objects.all()
    projects = Project.objects.filter(category=categories[index]).filter(language=request.LANGUAGE_CODE).order_by('order')
    return render(request, 'category.html', {'menu': 1, 'index': index, 'projects': projects})


def project(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'project.html', {'menu': 1, 'project': project})


def all_projects(request):
    projects = Project.objects.all().filter(language=request.LANGUAGE_CODE).order_by('category.id').order_by('order')
    return render(request, 'allprojects.html', {'menu': 1, 'projects': projects})

projects/templates/allprojects.html
{% extends "base.html" %}
{% load index %}
{% load static %}
{% load static i18n %}
{% block css %}
<link rel='stylesheet' href="{% static 'css/style.css' %}" media='screen' />

<script src="{% static 'js/blocksit.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $(window).load( function() {
            responsive();
        });
        $(window).resize(function() {
            responsive();
        });
        function responsive() {
            if ($('.container').width() < 576)
            {
                col = 1;
                // $('#container').width($('.container').width()-18);
            }
            else if ($('.container').width() < 768)
            {
                col = 2;
                // $('#container').width($('.container').width()-38);
            }
            else {
                col=3

            }
            $('#container').width($('.container').width());
            console.log($('.container').width());
            $('#container').BlocksIt({
                numOfCol: col,
                offsetX: 15,
                offsetY: 15
            });
        }
    });
    </script>
{% endblock %}
{% block content %}
<section id="wrapper">
    <div id="container">
        {% for project in projects %}
        <div class="grid">
            <div class="imgholder">
                <a href="{% url 'project' project.id %}"><img src="{{ project.image.url }}" width="100%" /></a>
            </div>
        </div>
        {% endfor %}

    </div>
</section>
<div class="text-center bottom-button" >
    <a class="font-segoe" href="{{request.META.HTTP_REFERER}}">{% trans 'Back' %}</a>
</div>
{% endblock %}
{% block script %}

{% endblock %}

projects/templates/base.html
{% load static i18n %} <!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>Lalo</title>
		<!-- Bootstrap core CSS -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
		<!-- Material Design Bootstrap -->
		<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.6.0/css/mdb.min.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" media="screen" href="{% static 'font/AtlanticCruise.css' %}" />
		<link rel="stylesheet" href="{% static 'css/mainpage.css' %}" />
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		{% block css %} {% endblock %}
	</head>
	<body style="transform: scale(0.84,0.84) translate(0%, -10%);">
		<div class="container" style="margin-bottom: 50px;">
			<div><a href="{% url 'index' %}" class="lang">{% trans 'Languages' %} </a></div>
			<div class="text-center logo">{% trans 'Lalo Valdivia' %}</div><br>
			<div class="row main-nav">
				<nav class="navbar navbar-expand-sm">
					<!-- Links -->
					<ul class="navbar-nav">
						<li class="nav-item {% if request.resolver_match.url_name == "bio" %}active{% endif %}"><a class="nav-link" href="{% url 'bio' %}">{% trans 'BIO' %}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'jobs' %}">{% trans 'PROJECTS' %}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">{% trans 'CONTACT' %}</a></li>
					</ul>
				</nav>
			</div>
			<div class="row categories-nav">
				<nav class="navbar navbar-expand-sm">
					<!-- Links -->
					<ul class="navbar-nav">
						<li class="nav-item"><a class="nav-link" href="{% url 'category' '0' %}">{% trans 'INSTITUTIONAL' %}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'category' '1' %}">{% trans 'FICTION / NON-FICTION' %}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'category' '2' %}">{% trans 'MUSIC' %}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'category' '3' %}">{% trans 'POLITICS' %}</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'category' '4' %}">{% trans 'ADVERTISING' %}</a></li>
					</ul>
				</nav>
			</div>
			{% block content %} {% endblock %}
		</div>
		<script>
			$(document).ready(function() {

				// $('a.nav-link').each(function(){
				// 	if($(this).text() == "{{ menu }}") $(this).addClass('active')
				// });
				$('.main-nav').find("a.nav-link:eq({{ menu }})").addClass('active');

				var category_index = "{{index}}"
				if(category_index != '')
				{
					$('.categories-nav').find("a.nav-link:eq({{ index }})").addClass('active');
				}
			});
		</script>
		{% block script %} {% endblock %}
	</body>
</html>

projects/templates/bio.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div style="font-size: 1.8rem; font-family: 'Segoe-UI'; margin:50px 25px;">
            <img style="padding: 40px;width: auto !important; max-width: 100% !important; float: right;" src="{{ image }}" align="top">

            {{ description|safe }}
        </div>
    </div>
{% endblock %}

projects/templates/category.html
{% extends "base.html" %}
{% load index %}
{% load static %}
{% load static i18n %}
{% block css %}
<link rel='stylesheet' href="{% static 'css/style.css' %}" media='screen' />

<script src="{% static 'js/blocksit.min.js' %}"></script>
<script>
    $(document).ready(function() {
        $(window).load( function() {
            responsive();
        });
        $(window).resize(function() {
            responsive();
        });
        function responsive() {
            if ($('.container').width() < 576)
            {
                col = 1;
                $('#container').width($('.container').width()-18);
            }
            else if ($('.container').width() < 768)
            {
                col = 2;
                $('#container').width($('.container').width()-38);
            }
            else {
                col=3
                $('#container').width($('.container').width()-50);

            }
            $('#container').BlocksIt({
                numOfCol: col,
                offsetX: 8,
                offsetY: 8
            });
        }
    });
    </script>
{% endblock %}
{% block content %}
<section id="wrapper">
    <div id="container">
        {% for project in projects %}
        <div class="grid">
            <div class="imgholder">
                <a href="{% url 'project' project.id %}"><img src="{{ project.image.url }}" width="100%" /></a>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<div class="text-center bottom-button" >
    <a href="{% url 'all_projects' %}">{% trans 'View all' %}</a>
</div>
{% endblock %}
{% block script %}

{% endblock %}

projects/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% load static i18n %}

{% block css %}
    <style>
        input {
            width: 100%;
            outline: none;
            font-family: "Arial";
        }
        form {
            padding-bottom: 16px; border-radius: 0px 0px 25px 25px;
        }
        form .row {
            margin: 0 10px;
        }
        .header div{

            border-bottom: 3px solid white;
        }
        .header div, form .col-md-12 {
            padding: 8px !important;
        }
        p{
            margin-bottom: 0.5rem;
        }
        form {
            margin: 0 20px;
            background: black;
            color: white;
            text-align: center;
            font-family: "AtlanticCruise"
        }
        textarea {
            width: 100%;
            resize: none;
            outline: none;
            font-family: "Arial";
        }
        #btn_submit {
            background: transparent;
            color: white;
            border: none;
            height: 100%;
            cursor: pointer;
            padding: 10px 0px;
        }
        #contact {
            margin: 0 auto;
        }

        @media (max-width: 575px) { #contact { width: 70%; } .border-right { border-right: none !important; } }
        @media (min-width: 576px) { #contact { width: 400px; } .border-right { border-right: none !important; } }
        @media (min-width: 768px) { #contact { width: 500px; } .border-right { border-right: 3px solid white !important; } }

        .alert {
            width: 50%;
            margin: 20px auto;
        }

        #imdb {
            width: 48px;
            height: 48px;
            position: relative;
            left:  103.5%;
            bottom: 21.5%
        }
        #datos {
            position: relative;
            bottom: -25%;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div id="contact">
            <img src="{% static 'image/media.png' %}">
            <form method="POST">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {{ form.source.errors }}
                {{ form.source }}

                <div class="row header">
                    <div class="col-md-3 border-right">
                        <p>{% trans 'NAME' %}</p>
                        {{ form.name }}
                    </div>
                    <div class="col-md-5 border-right">
                        <p>{% trans 'E-MAIL' %}</p>
                        {{ form.from_email }}
                    </div>
                    <div class="col-md-4">
                        <p>{% trans 'SUBJECT' %}</p>
                        {{ form.affair }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12"><p style="margin-bottom: -8px; text-align: left;">{% trans 'MESSAGE' %}</p></div>
                    <div class="col-md-12">{{ form.message }}</div>
                </div>
                <div class="row">
                    <div class="col-md-8 border-right" style="text-align: left; border-top: 3px solid white;">

                            <div id="datos">lalov311@gmail.com &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; +51 995 054 016</div>

                    </div>
                    <div class="col-md-4" style="border-top: 3px solid white;"><input id="btn_submit" type="button" value="{% trans 'SEND' %}"></div>
                </div>
            </form>
                    <div id="imdb"><a href="https://m.imdb.com/name/nm5318515/" target="_blank"><img src="{% static 'image/imdb.png' %}"></a><br><br><a href="https://www.linkedin.com/in/jevaldiviabrunetti/" target="_blank"><img src="{% static 'image/linkedin.png' %}"></a></div>
        </div>

    </div>
{% endblock %}


{% block script %}
    <script src="{% static 'js/notify.min.js' %}"></script>
    <script>
        $('#btn_submit').click(function() {
            $.ajax({
                type: 'POST',
                url: '',
                data: {

                    name: $('#id_name').val(),
                    from_email: $('#id_from_email').val(),
                    affair: $('#id_affair').val(),
                    message: $('#id_message').val(),
                    csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function(resultData) {
                    if(resultData == 'Success') {
                        $.notify("{% trans 'Email sent successfully!' %}", "success");
                    }
                    else {
                        $.notify("{% trans 'Email sent Failed!' %}", "error");
                    }
                }
            });
        });

    </script>
{% endblock script %}

projects/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lalo</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'font/AtlanticCruise.css' %}" />
    <link rel="stylesheet" media="screen" href="{% static 'css/firstpage.css' %}">

</head>
<body>
    <div class="container-fluid homepage">
        <div class="row">
            <div class="col-md-12 text-center"><div class="logo">Lalo Valdivia</div></div>
        </div>
        <div class="row">

            <div class="col-md-6 text-center"><div class="lang"><a href="{% url 'en_jobs' %}">English</a></div></div>
            <div class="col-md-6 text-center"><div class="lang"><a href="{% url 'jobs' %}">Español</a></div></div>
        </div>
    </div>
</body>
</html>

projects/templates/jobs.html
{% extends "base.html" %}
{% load index %}
{% load static i18n %}
{% block content %}
    <div class="row">
        {% for category in categories %}

            {% with forloop.counter0 as idx %}
                {% if idx > 0 and idx|divisibleby:3 %}
                    </div><div class="row">
                    {% with idx|div:3 as rowIndex and categories|count as length %}
                        {% if rowIndex == length|div:3 %}
                            {% if length|mod:3 == 1 %}
                                <div class="offset-md-4 col-md-4">
                            {% elif length|mod:3 == 2 %}
                                <div class="offset-md-2 col-md-4">
                            {% else %}
                                <div class="col-md-4">
                            {% endif %}
                        {% else %}
                            <div class="col-md-4">
                        {% endif %}
                    {% endwith %}
                {% else %}
                    <div class="col-md-4">
                {% endif %}
            {% endwith %}
                <div class="image view overlay">
                    <img src="{{ category.image.url }}" category="{% trans category.category.name %}" class="img-fluid " alt="sample image">
                    <a href="{% url 'category' category.category.id|minus:1 %}" class="mask flex-center rgba-grey-strong text-center font-segoe">
                        <p>{% trans category.category.name %}</p>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="text-center bottom-button" >
        <a href="{% url 'all_projects' %}">{% trans 'View all' %}</a>
    </div>
{% endblock %}

projects/templates/project.html
{% extends "base.html" %}
{% load static i18n %}
{% block content %}
    <div class="row job_details">
        <div class="offset-md-2 col-md-8 offset-sm-1 col-sm-10">
            <p style="font-size: 2rem;">{{ project.title }}</p>

            {% if project.is_shown %}
            <div style="width: 80%; margin: 30px auto;"><img style="margin: 0px auto; width: 100%;" src="{{ project.image.url }}"></div>
            {% endif %}

            {% if project.video %}
                <div style="width: 80%; margin: 30px auto;">
                    <iframe width="100%" style="margin: 0 auto;" src="{{ project.video }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            {% endif %}

            <p>{{ project.description|safe }}</p>
        </div>
    </div>
    <div class="text-center bottom-button" >
        <a class="font-segoe" href="{{request.META.HTTP_REFERER}}">{% trans 'Back' %}</a>
    </div>
    <script>
        $(document).ready(function() {
            $('iframe').height($('iframe').width() * 0.5625);
        });
        $(window).resize(function() {
            $('iframe').height($('iframe').width() * 0.5625);
        });
    </script>
{% endblock %}